### ISSUE TITLE
Error when trying to launch model

### ISSUE THREAD

**Issue by alexanderbkl** [ntfargo/TextGenWebUI-Colab#1]
Error when trying to launch last part of the notebook:

/content/drive/MyDrive/text-generation-webui
Do you want to enable authentication? (yes/no): no
Gradio HTTP request redirected to localhost :)
Warning: the gradio "share link" feature downloads a proprietary and
unaudited blob to create a reverse tunnel. This is potentially dangerous.

2023-05-14 21:09:44.927846: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
bin /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so
Loading gpt4-x-vicuna-13b-native-4bit-128g...
Found the following quantized model: models/gpt4-x-vicuna-13b-native-4bit-128g/vicuna-13b-4bit-128g.safetensors
Loading model ...
Done.
Loaded the model in 57.96 seconds.
Loading the extension "gallery"... Ok.
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /content/drive/MyDrive/text-generation-webui/server.py:927 in <module>       │
│                                                                              │
│   924 │   │   })                                                             │
│   925 │                                                                      │
│   926 │   # Launch the web UI                                                │
│ ❱ 927 │   create_interface()                                                 │
│   928 │   while True:                                                        │
│   929 │   │   time.sleep(0.5)                                                │
│   930 │   │   if shared.need_restart:                                        │
│                                                                              │
│ /content/drive/MyDrive/text-generation-webui/server.py:514 in                │
│ create_interface                                                             │
│                                                                              │
│   511 │   if shared.args.extensions is not None and len(shared.args.extensio │
│   512 │   │   extensions_module.load_extensions()                            │
│   513 │                                                                      │
│ ❱ 514 │   with gr.Blocks(css=ui.css if not shared.is_chat() else ui.css + ui │
│   515 │   │                                                                  │
│   516 │   │   # Create chat mode interface                                   │
│   517 │   │   if shared.is_chat():                                           │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/gradio/blocks.py:1285 in __exit__    │
│                                                                              │
│   1282 │   │   │   Context.root_block = None                                 │
│   1283 │   │   else:                                                         │
│   1284 │   │   │   self.parent.children.extend(self.children)                │
│ ❱ 1285 │   │   self.config = self.get_config_file()                          │
│   1286 │   │   self.app = routes.App.create_app(self)                        │
│   1287 │   │   self.progress_tracking = any(block_fn.tracks_progress for blo │
│   1288 │   │   self.exited = True                                            │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/gradio/blocks.py:1261 in             │
│ get_config_file                                                              │
│                                                                              │
│   1258 │   │   │   │   assert isinstance(block, serializing.Serializable)    │
│   1259 │   │   │   │   block_config["serializer"] = serializer               │
│   1260 │   │   │   │   block_config["info"] = {                              │
│ ❱ 1261 │   │   │   │   │   "input": list(block.input_api_info()),  # type: i │
│   1262 │   │   │   │   │   "output": list(block.output_api_info()),  # type: │
│   1263 │   │   │   │   }                                                     │
│   1264 │   │   │   config["components"].append(block_config)                 │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/gradio_client/serializing.py:41 in   │
│ input_api_info                                                               │
│                                                                              │
│    38 │   # For backwards compatibility                                      │
│    39 │   def input_api_info(self) -> tuple[str, str]:                       │
│    40 │   │   api_info = self.api_info()                                     │
│ ❱  41 │   │   return (api_info["serialized_input"][0], api_info["serialized_ │
│    42 │                                                                      │
│    43 │   # For backwards compatibility                                      │
│    44 │   def output_api_info(self) -> tuple[str, str]:                      │
╰──────────────────────────────────────────────────────────────────────────────╯
KeyError: 'serialized_input'

**Comment by alexanderbkl** [comment]
I'm running Colab free, maybe that is the issue

**Comment by ntfargo** [comment]
You need upgrade gradio, add this `!pip install --force gradio==3.28.3` after `!pip install -r requirements.txt`

**Comment by alexanderbkl** [comment]
Worked with an older version `!pip install --force gradio==3.26.0` and works charms on a free Colab environment, thanks a lot!
